# Generated by Django 4.2.1 on 2023-06-01 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(default=45, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
